[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py seed_data --no-input 2>/dev/null || true && gunicorn sewingshop.wsgi --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
