# Generated by Django 4.2.30 on 2026-05-07 21:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('thread', 'Thread'), ('button', 'Buttons & Fasteners'), ('lining', 'Lining'), ('zipper', 'Zippers'), ('trim', 'Trim & Lace'), ('accessory', 'Accessory'), ('other', 'Other')], default='fabric', max_length=20)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('yd', 'Yards'), ('units', 'Units / Pieces'), ('roll', 'Rolls'), ('spool', 'Spools'), ('kg', 'Kilograms')], default='m', max_length=10)),
                ('supplier', models.CharField(blank=True, help_text='Optional supplier / vendor name', max_length=200)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Indicative cost per default unit', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'color')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('yd', 'Yards'), ('units', 'Units / Pieces'), ('roll', 'Rolls'), ('spool', 'Spools'), ('kg', 'Kilograms')], default='m', help_text='Unit used for this garment (defaults to material default)', max_length=10)),
                ('color_override', models.CharField(blank=True, help_text='Override the catalog color for this item if needed', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='shop.material')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='shop.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Material',
                'verbose_name_plural': 'Order Item Materials',
                'ordering': ['order_item', 'material'],
            },
        ),
    ]
