# Generated by Django 4.2.30 on 2026-05-09 21:48

import secrets
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _backfill_referral_codes(apps, schema_editor):
    Customer = apps.get_model('shop', 'Customer')
    used = set(
        Customer.objects.exclude(referral_code='').values_list('referral_code', flat=True)
    )
    for customer in Customer.objects.filter(referral_code=''):
        for _ in range(20):
            code = 'CDP-' + secrets.token_hex(3).upper()
            if code not in used:
                used.add(code)
                customer.referral_code = code
                customer.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('kind', models.CharField(choices=[('flat', 'Flat amount'), ('per_unit', 'Per unit')], default='flat', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Add-on',
                'verbose_name_plural': 'Add-ons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 e.g. EUR, USD, GBP', max_length=3, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(default='€', max_length=8)),
                ('is_base', models.BooleanField(default=False, help_text='Exactly one row should be the base.')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiply the base price by this value (1.00 = no change).', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fabric Type',
                'verbose_name_plural': 'Fabric Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GarmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Base price in EUR before fabric/add-ons/urgency.', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Garment Category',
                'verbose_name_plural': 'Garment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('thread', 'Thread'), ('zipper', 'Zipper'), ('button', 'Button'), ('lining', 'Lining'), ('trim', 'Trim'), ('other', 'Other')], default='fabric', max_length=20)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('default_unit', models.CharField(choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('unit', 'Units'), ('roll', 'Rolls'), ('spool', 'Spools')], default='m', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stock_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short label e.g. S-A12, H-03', max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('shelf', 'Shelf'), ('hanger', 'Hanger'), ('bin', 'Bin'), ('rail', 'Rail'), ('drawer', 'Drawer')], default='shelf', max_length=10)),
                ('area', models.CharField(blank=True, help_text='Workshop zone or room', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Typical days from order placed to delivery.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('placed_on', models.DateField(blank=True, null=True)),
                ('expected_on', models.DateField(blank=True, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Order',
                'verbose_name_plural': 'Supplier Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UrgencySurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], help_text='Matches CustomerOrder.priority.', max_length=10, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Urgency Surcharge',
                'verbose_name_plural': 'Urgency Surcharges',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_styles',
            field=models.JSONField(blank=True, default=dict, help_text='Saved garment style preferences as JSON'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.RunPython(_backfill_referral_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='applied_discount_code',
            field=models.CharField(blank=True, help_text='Referral or discount code that was applied at booking time.', max_length=40),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='base_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount converted to base currency at booking. Frozen.', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='base_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal converted to base currency at booking. Frozen.', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notes shared by the customer at booking; flow into all child tickets as design notes.'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate from order currency to base (EUR) at booking. Frozen.', max_digits=12),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen snapshot of every pricing rule and rate used. Read-only after booking.'),
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_lines', to='shop.material')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.supplierorder')),
            ],
            options={
                'verbose_name': 'Supplier order line',
                'verbose_name_plural': 'Supplier order lines',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount percent applied to a redeeming new customer order.', max_digits=5)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_referral_code', to='shop.customer')),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='shop.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('snapshot', models.JSONField(default=dict, help_text='Items + measurements + notes captured from a past order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_templates', to='shop.customer')),
            ],
            options={
                'verbose_name': 'Order template',
                'verbose_name_plural': 'Order templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit at time of consumption. Frozen.', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='shop.material')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='shop.orderitem')),
            ],
            options={
                'verbose_name': 'Material consumption',
                'verbose_name_plural': 'Material consumptions',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.customerorder')),
            ],
            options={
                'verbose_name': 'Order event',
                'verbose_name_plural': 'Order events',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='Event name from shop/events.py', max_length=80)),
                ('channel', models.CharField(choices=[('inapp', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('recipient', models.CharField(help_text='Email, phone, or username', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification log',
                'verbose_name_plural': 'Notification log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to supplier order'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_decisions', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='shop.material')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='shop.employee')),
                ('supplier_order', models.ForeignKey(blank=True, help_text='Set when the request is converted to a supplier order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='shop.supplierorder')),
            ],
            options={
                'verbose_name': 'Material Request',
                'verbose_name_plural': 'Material Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='shop.storagelocation'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='shop.supplier'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('garment_type', models.CharField(max_length=120)),
                ('fabric', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=5)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='shop.customer')),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='shop.customerorder')),
            ],
            options={
                'verbose_name': 'Intake lead',
                'verbose_name_plural': 'Intake leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=5)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total in the order currency. Frozen at issue time.', max_digits=10)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('pdf_path', models.CharField(blank=True, max_length=400)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='shop.customerorder')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount (EUR)')], default='percentage', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_orders', models.PositiveIntegerField(default=0, help_text='Customer must already have at least this many delivered orders.')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Leave blank for a public code.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='shop.customer')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='shop.customerorder')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='shop.customer')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to='shop.customer')),
            ],
            options={
                'verbose_name': 'Customer Referral',
                'verbose_name_plural': 'Customer Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fitting', 'Fitting'), ('alteration', 'Alteration'), ('pickup', 'Pickup'), ('intake', 'Intake consultation')], default='fitting', max_length=15)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('location', models.CharField(blank=True, default='Costuras de Paqui · C. de San Enrique 16, Madrid', max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='requested', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='shop.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='shop.customerorder')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferring_customers', to='shop.currency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferring_customers', to='shop.storagelocation'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Display currency at booking time. Frozen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.currency'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='Where the physical garment is stored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to='shop.storagelocation'),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('inapp', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification preference',
                'verbose_name_plural': 'Notification preferences',
                'unique_together': {('user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_base', models.DecimalField(decimal_places=6, help_text='Multiply an amount in this currency by this value to get the base currency.', max_digits=14)),
                ('captured_on', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default='manual', max_length=80)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shop.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-captured_on'],
                'unique_together': {('currency', 'captured_on')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. order.transition, payment.recorded, material.approved', max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='shop_auditl_target__e11f2b_idx'), models.Index(fields=['action'], name='shop_auditl_action_565f32_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('kind', models.CharField(choices=[('reference', 'Reference image'), ('progress', 'Progress photo'), ('final', 'Final product'), ('receipt', 'Receipt'), ('intake', 'Intake submission'), ('other', 'Other')], default='reference', max_length=15)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='shop_attach_content_47a4c1_idx')],
            },
        ),
    ]
