# Generated by Django 4.2.30 on 2026-05-07 21:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_material_orderitemmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional user account that grants access to the self service portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='payment_option',
            field=models.CharField(choices=[('full_advance', 'Full Advance'), ('deposit_and_final', 'Deposit and Final Payment'), ('partial_payments', 'Partial Payments'), ('full_on_delivery', 'Full on Delivery'), ('immediate_full', 'Immediate Full')], default='full_on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='received_by',
            field=models.CharField(blank=True, help_text='Name of the person who received the delivery.', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to a Django user account when the employee logs in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('thread', 'Thread'), ('button', 'Buttons and Fasteners'), ('lining', 'Lining'), ('zipper', 'Zippers'), ('trim', 'Trim and Lace'), ('accessory', 'Accessory'), ('other', 'Other')], default='fabric', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='default_unit',
            field=models.CharField(choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('yd', 'Yards'), ('units', 'Units'), ('roll', 'Rolls'), ('spool', 'Spools'), ('kg', 'Kilograms')], default='m', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, help_text='Optional supplier or vendor name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Indicative cost per default unit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(help_text='The kind of measurement, for example bust, waist or sleeve length.', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='garment_type',
            field=models.CharField(help_text='The kind of garment, for example dress, suit or blouse.', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='An item level discount expressed as an amount.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size_label',
            field=models.CharField(blank=True, help_text='A size label such as S, M, L or a custom size description.', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitemmaterial',
            name='color_override',
            field=models.CharField(blank=True, help_text='An optional color override for this garment.', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitemmaterial',
            name='unit',
            field=models.CharField(choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('yd', 'Yards'), ('units', 'Units'), ('roll', 'Rolls'), ('spool', 'Spools'), ('kg', 'Kilograms')], default='m', help_text='Unit used for this garment, defaulting to the catalog default.', max_length=10),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='stage_order',
            field=models.PositiveIntegerField(help_text='A lower number means an earlier stage in the production pipeline.'),
        ),
    ]
